### ISSUE TITLE
possiblity to add script running for VM modification in shutdown state 

### ISSUE THREAD

**Issue by MichalHajduch** [tomaustin700/HyperDeploy#14]
great job, just im seaching for possibility to run powershell script when machine is down to modify machine settings

**Comment by tomaustin700** [comment]
Hi @MichalHajduch, I can add that. Can you tell me a bit more about your use case? Thanks

**Comment by MichalHajduch** [comment]
Hi Tomas, for example i have trunk mode on all machines by Virtual switch and i need assign different vlans on machine. your script works fine, but if  want to use post scripts, i cannot because different vlans are not configured. so it should be very useful to have possiblity to run script in shutdown state after machine is created
Thanks!

**Comment by tomaustin700** [comment]
Hi @MichalHajduch, please see #15 which implements the changes you have requested. If you are happy with it or have further suggestions then please let me know and I can either merge and release an upgrade or make changes. Thanks Tom.

**Comment by tomaustin700** [comment]
@MichalHajduch I have just released v0.3.0 which has this new functionality, please run `Update-Module HyperDeploy` to get the latest version. You can double check what version you have by running `Get-InstalledModule HyperDeploy`

![image](https://user-images.githubusercontent.com/6324102/188318368-424941d2-1c18-4ac6-98bd-0490ebc085e5.png)
